spring:
  application:
    name: dubbo-consumer-demo
dubbo:
  registry:
    address: zookeeper://127.0.0.1   #注册中心的ip可以直接加上端口，也可以同下面的port设置
    timeout: 6000   #超时时间设置，太短可能会报错单位是  ms也就是6秒
    port: 2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  provider:
    version: 1.0.0